{
    "name": "Interior Finishing Management",
    "summary": "End-to-end operations suite for interior finishing companies",
    "version": "18.0.1.0.0",
    "author": "Interior Finishing SaaS",
    "license": "LGPL-3",
    "category": "Project",
    "depends": [
        "base",
        "mail",
        "hr",
        "crm",
        "project",
        "purchase",
        "stock",
        "account",
        "web",
    ],
    "data": [
        "security/interior_security.xml",
        "security/ir.model.access.csv",
        "data/cron.xml",
        "views/menu.xml",
        "views/project_views.xml",
        "views/engineer_views.xml",
        "views/finance_views.xml",
        "views/procurement_views.xml",
        "views/inventory_views.xml",
        "views/document_views.xml",
        "views/dashboard_views.xml",
        "reports/project_report_templates.xml",
        "reports/project_report_actions.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "interior_finishing_management/static/src/js/chart.min.js",
            "interior_finishing_management/static/src/js/dashboard_action.js",
            "interior_finishing_management/static/src/xml/dashboard_templates.xml",
            "interior_finishing_management/static/src/scss/dashboard.scss",
        ],
    },
    "application": True,
    "installable": True,
}
